### PR TITLE
Avoid warning from esmith::util::isValidIP()

### PR DESCRIPTION
**Pull request by stephdl**
The function doesn't accept empty value ('')

PLease can you accept my PR, my code is broken with the function 'isValidIP'

### CODE REVIEW

**Comment by stephdl** [comment]
I'm working on nfs and I use the function isValidIP of /usr/share/perl5/vendor_perl/esmith/util/network.pm. When I use the function with an empty value I have the message

`WARNING in /etc/e-smith/templates//etc/exports/10exports: Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/esmith/util/network.pm line 133.`

I suppose that it is the same for NS6

BTW this bug has been corrected on SME :p

**Review by DavidePrincipi — APPROVED** [review]
IIUC I'd change the PR title to "Avoid warning from esmith::util::isValidIP()"

**Comment by stephdl** [comment]
cool I need it for nethserver-nfs

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-lib-2.2.1-1.3.g6edae36.ns7.noarch.rpm

----
@stephdl ring me when you're ready to release!

**Comment by stephdl** [comment]
Verification
```
[root@NS7DEV3 ~]# rpm -qa nethserver-lib
nethserver-lib-2.2.1-1.ns7.noarch


[root@NS7DEV3 ~]# expand-template /etc/exports 
WARNING in /etc/e-smith/templates//etc/exports/10exports: Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/esmith/util/network.pm line 133.
WARNING: Template processing succeeded for //etc/exports: 1 fragment generated warnings
 at /sbin/e-smith/expand-template line 45.
```

the line of code with create the undefined value is 

```
sub isValidIP($)
{
    my ($string) = @_;
    return $string eq ipv4_chkip($string);
}
```
I upgrade to the version of nethserve-testing

```
[root@NS7DEV3 ~]# rpm -qa nethserver-lib
nethserver-lib-2.2.1-1.3.g6edae36.ns7.noarch
```
then I use my code

`[root@NS7DEV3 ~]# expand-template /etc/exports `

no error :) and we can see the change
```
sub isValidIP($)
{
    my ($string) = @_;
    return unless defined ipv4_chkip($string);
    return $string eq ipv4_chkip($string);
}
```

marked verified

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-lib-2.2.2-1.ns7.noarch.rpm

**Pull request merged**
