### PR TITLE
Update template-begin

### PR DESCRIPTION
**Pull request by gsanchietti**
- Change copyright date and developer guide url

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
I'd remove the copyright paragraph:

- it does not list contributions
- I'm not sure a configuration file can be subject to copyrights

**Comment by filippocarletti** [comment]
I think that configuration files may be subject to copyright. They often are the result of study and work, to make the software behave as desired.

**Comment by DavidePrincipi** [comment]
Some food for thought:

- https://www.quora.com/Should-software-configuration-files-be-licensed
- https://groups.drupal.org/node/17555

**Comment by gsanchietti** [comment]
Can I merge this one as is?

**Pull request merged**
